Safe duck/who we are section
acm-ucr/asme-website pull request #23
Opened 2023-07-01 18:37 UTC by SafeDuck

button inverts color on hover
![image](https://github.com/acm-ucr/asme-website/assets/49844738/ddbc3dde-8dcc-4d87-9073-bbb5ae7d5881)

2023-07-01 18:47 UTC, shahdivyank commented on src/components/WhoWeAreSection.jsx
> +            <div className="bg-white absolute mt-2 mx-28 px-4 text-[#38769F] font-poppins font-bold p-1 text-2xl inline-flex items-center">
```suggestion
            <div className="bg-white absolute mt-2 mx-28 px-4 text-[#38769F] font-poppins font-bold p-1 text-2xl inline-flex items-center">
```

Use the Tailwind Colors:

ex. `bg-asme-blue-100`

2023-07-01 18:48 UTC, shahdivyank requested changes

2023-07-01 18:48 UTC, shahdivyank commented on src/components/WhoWeAreSection.jsx
> +            <div className="bg-[#1A5582] w-2 h-full inline-block right-0 top-3 absolute "></div>
Use Tailwind colors

2023-07-02 21:50 UTC, menthy-wu approved these changes

2023-07-02 21:52 UTC, menthy-wu approved these changes

2023-07-02 21:53 UTC, menthy-wu approved these changes

2023-07-02 22:08 UTC, shahdivyank approved these changes

2023-07-02 22:08 UTC, merged